language: generic
sudo: required

services:
  - docker

before_install:
- docker pull unruh/isacrypt:prereqs

script:
- docker run -v "$PWD:/home/user/data" unruh/isacrypt:prereqs isabelle build -d . IsaCrypt-Nodocs
