language: generic
sudo: required

services:
  - docker

before_install:
- docker pull unruh/isabelle:multivariate

script:
- docker run -v "$PWD:/home/user/data" unruh/isabelle:multivariate isabelle build -d . IsaCrypt
