language: python
sudo: required

python:
- "3.4"

services:
- docker

before_install:
- docker pull unruh/isabelle:isacrypt-prereqs

install:
- pip3 install pyro4 serpent

script:
- touch test.tmp # Checking for write access in current dir
- test -e test.tmp
- make test_with_docker
#- docker run -v "$PWD:/home/user/data" unruh/isabelle:isacrypt-prereqs isabelle build -d . IsaCrypt-Nodocs
