language: generic
sudo: required

services:
  - docker

before_install:
- docker pull unruh/isabelle:isacrypt-prereqs

script:
- docker run -v "$PWD:/home/user/data" unruh/isabelle:isacrypt-prereqs isabelle build -d . IsaCrypt-Nodocs
