#!/bin/bash

HEAP=IsaCrypt-Core
ISADIR=/opt/Isabelle2015

git pull 

if [ "$1" = "x" ]; then
    HEAP=IsaCrypt-Prereqs
    shift
fi

( 
    "$ISADIR"/bin/isabelle jedit -l "$HEAP" -d . "$@"
    git-gui
    git push
) &
