#!/bin/bash

HEAP=IsaCrypt-Prereqs
ISADIR=/opt/Isabelle2016-1

git pull &

if [ "$1" = "x" ]; then
    HEAP=IsaCrypt-Core
    shift
fi

( 
    "$ISADIR"/bin/isabelle jedit -l "$HEAP" -d . "$@"
    git gui
    git push
) &
